### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by HaryoPratama** [AlexFlipnote/birthday.py#1]
Hey i need help with this
![image](https://user-images.githubusercontent.com/62017665/82512409-8eb84380-9aff-11ea-8950-629edfaff960.png)

**Comment by AlexFlipnote** [comment]
Use Python3

**Comment by HaryoPratama** [comment]
ok i try

**Comment by HaryoPratama** [comment]
3 is version?

**Comment by AlexFlipnote** [comment]
Not going to spoon-feed, use Google...
